#!/usr/bin/env bash
# Create or rotate the website-lambda secrets in AWS Secrets Manager, and
# (optionally) grant the Lambda execution role permission to read them.
#
# The Lambda never stores SESSION_SECRET / IMS_CLIENT_SECRET in plaintext env
# (Adobe AWS Security Standard). env.<target>.json carries only the non-secret
# ids (SESSION_SECRET_ID / IMS_CLIENT_SECRET_ID); lib/secrets.js fetches the
# values at runtime. This script manages the values behind those ids. See
# SECRETS.md for the console equivalent and the full walkthrough.
#
# Idempotent: creates a secret if absent, otherwise stores a new value (rotate).
# Values are passed to the AWS CLI via a 0600 temp file (never on the command
# line), so they don't land in `ps` output or shell history.
#
# Run it yourself (auto mode blocks AWS write calls).
#
# Usage:
#   TARGET=stage ./set-secrets.sh                 # rotate both (generate session, prompt IMS)
#   TARGET=stage SESSION_ONLY=1 ./set-secrets.sh  # only the session secret
#   TARGET=stage IMS_ONLY=1 ./set-secrets.sh      # only the IMS client secret
#   TARGET=prod  GRANT_ROLE=1 ./set-secrets.sh    # also attach the IAM read policy
#
# Value sources (optional; interactive fallbacks otherwise):
#   SESSION_SECRET_VALUE   - use this instead of generating one (openssl rand)
#   IMS_CLIENT_SECRET_VALUE- use this instead of prompting
#   GRANT_ROLE=1           - also put the GetSecretValue policy on the role
#   ROLE_NAME              - execution role (default: read from the function)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
[ -f "$SCRIPT_DIR/deploy.env" ] && . "$SCRIPT_DIR/deploy.env"

# Send AWS CLI output straight to the console instead of through a pager (less).
export AWS_PAGER=""

PROFILE="${AWS_PROFILE:-default}"
REGION="${AWS_REGION:-us-east-2}"

TARGET="${TARGET:-prod}"
case "$TARGET" in
  prod|stage) ;;
  *) echo "ERROR: TARGET must be 'prod' or 'stage' (got '$TARGET')." >&2; exit 1 ;;
esac

# Secret names are namespaced by target so prod and stage never collide, and a
# single IAM policy can wildcard the whole "spectrum-hub/<target>/" prefix.
PREFIX="spectrum-hub/${TARGET}"
SESSION_SECRET_NAME="${SESSION_SECRET_NAME:-$PREFIX/session-secret}"
IMS_CLIENT_SECRET_NAME="${IMS_CLIENT_SECRET_NAME:-$PREFIX/ims-client-secret}"

aws_sm() { aws secretsmanager "$@" --profile "$PROFILE" --region "$REGION"; }

# Create the secret if it does not exist yet, otherwise store a new version
# (rotation). Reads the value from a private temp file, never the command line.
upsert_secret() {
  local name="$1" value="$2" tmp
  tmp="$(mktemp)"; chmod 600 "$tmp"
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN
  printf '%s' "$value" > "$tmp"
  if aws_sm describe-secret --secret-id "$name" >/dev/null 2>&1; then
    aws_sm put-secret-value --secret-id "$name" --secret-string "file://$tmp" \
      --query '{name:Name,version:VersionId}' --output table
    echo "  rotated: $name"
  else
    aws_sm create-secret --name "$name" \
      --description "website-lambda ($TARGET) secret; value read at runtime by lib/secrets.js" \
      --secret-string "file://$tmp" --query '{name:Name,arn:ARN}' --output table
    echo "  created: $name"
  fi
}

do_session=1; do_ims=1
[ "${IMS_ONLY:-0}" = "1" ] && do_session=0
[ "${SESSION_ONLY:-0}" = "1" ] && do_ims=0

if [ "$do_session" = "1" ]; then
  # SESSION_SECRET is an HMAC key with no external dependency, so a fresh random
  # one is generated by default. Pass SESSION_SECRET_VALUE to reuse a known key.
  session_value="${SESSION_SECRET_VALUE:-}"
  if [ -z "$session_value" ]; then
    session_value="$(openssl rand -base64 32)"
    echo "Generated a new SESSION_SECRET (32 random bytes, base64)."
  fi
  echo "Storing $SESSION_SECRET_NAME ..."
  upsert_secret "$SESSION_SECRET_NAME" "$session_value"
fi

if [ "$do_ims" = "1" ]; then
  # IMS_CLIENT_SECRET is issued by Adobe IMS (Developer Console) - it cannot be
  # generated here. Provide it via env or the hidden prompt.
  ims_value="${IMS_CLIENT_SECRET_VALUE:-}"
  if [ -z "$ims_value" ]; then
    read -rs -p "Enter IMS_CLIENT_SECRET for $TARGET (input hidden): " ims_value; echo
  fi
  [ -z "$ims_value" ] && { echo "ERROR: IMS_CLIENT_SECRET value is empty." >&2; exit 1; }
  echo "Storing $IMS_CLIENT_SECRET_NAME ..."
  upsert_secret "$IMS_CLIENT_SECRET_NAME" "$ims_value"
fi

# Optional: grant the Lambda execution role permission to read this target's
# secrets. IAM is account-wide, so it is opt-in (GRANT_ROLE=1). The role is read
# from the deployed function when ROLE_NAME is not given.
if [ "${GRANT_ROLE:-0}" = "1" ]; then
  FUNCTION_NAME="${FUNCTION_NAME:-spectrum-${TARGET}-lambda-proxy}"
  if [ -z "${ROLE_NAME:-}" ]; then
    ROLE_ARN="$(aws lambda get-function-configuration --function-name "$FUNCTION_NAME" \
      --profile "$PROFILE" --region "$REGION" --query 'Role' --output text)"
    ROLE_NAME="${ROLE_ARN##*/}"
  fi
  ACCOUNT="$(aws sts get-caller-identity --profile "$PROFILE" --query Account --output text)"
  RESOURCE="arn:aws:secretsmanager:${REGION}:${ACCOUNT}:secret:${PREFIX}/*"
  echo "Granting secretsmanager:GetSecretValue on $RESOURCE to role $ROLE_NAME ..."
  aws iam put-role-policy --role-name "$ROLE_NAME" \
    --policy-name "website-lambda-secrets-read-${TARGET}" \
    --policy-document "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"secretsmanager:GetSecretValue\",\"Resource\":\"$RESOURCE\"}]}" \
    --profile "$PROFILE"
  echo "  granted."
fi

cat <<EOF

Done. Put these ids in env.${TARGET}.json (and remove any plaintext
SESSION_SECRET / IMS_CLIENT_SECRET), then redeploy with TARGET=${TARGET} ./deploy.sh:

  "SESSION_SECRET_ID": "${SESSION_SECRET_NAME}",
  "IMS_CLIENT_SECRET_ID": "${IMS_CLIENT_SECRET_NAME}",

If you did not pass GRANT_ROLE=1, grant the execution role
secretsmanager:GetSecretValue on arn:aws:secretsmanager:${REGION}:<account>:secret:${PREFIX}/*
(see SECRETS.md).
EOF
